Feature/tk 1 create classes
jordan-hanson/CashRegister pull request #1
Opened 2022-01-17 00:26 UTC by jordan-hanson

2022-01-24 21:49 UTC, kappamax requested changes
Can you use .gitignore to ignore all your .gradle and .idea files, which will make your changes and PRs look a lot easier to read through?

2022-01-24 21:53 UTC, kappamax commented on src/main/java/CashDrawer.java
> +        return "$" + total +
Do you know the difference between "$" + total + " " + twenty and a String builder vs a String formatter?

This one deserves some looking into. Here are some great reads about this.
https://kylewbanks.com/blog/java-string-concatenation-vs-stringbuilder-vs-string-format-performance
https://www.baeldung.com/java-string-performance

2022-01-24 21:54 UTC, jordan-hanson commented
Ya I have it, but I’m not sure why it isn’t working. I think when I tried creating a jar file I changed a configuration somewhere. Any ideas??

Sent from my iPhone

> On Jan 24, 2022, at 2:49 PM, Kirk Lashley ***@***.***> wrote:
> 
> ﻿
> @kappamax requested changes on this pull request.
> 
> Can you use .gitignore to ignore all your .gradle and .idea files, which will make your changes and PRs look a lot easier to read through?
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
> You are receiving this because you authored the thread.

2022-01-24 21:54 UTC, kappamax commented on src/main/java/CashDrawer.java
> +    int twenty;
Should these have private of public or package access modifiers? Rec you make them private.

2022-01-24 21:56 UTC, kappamax commented on src/main/java/CashDrawer.java
> +    public CashDrawer(int twenty, int ten, int five, int two, int one) {
This constructor is interesting, with the implementation, what happens if you pass in negative numbers into the args? Can the register end up in an invalid state?

2022-01-25 18:39 UTC, KrbAlmryde commented on src/main/java/CashDrawer.java
> +        return "$" + total +
2nd the StringBuilder or String Formatter approach. From a performance standpoint its pretty wild just how inefficient string concatenation is. Also, pro-tip, this is a common java interview question (or was) so good to have in your back pocket ;)

2022-01-25 18:53 UTC, KrbAlmryde commented
> Ya I have it, but I’m not sure why it isn’t working. I think when I tried creating a jar file I changed a configuration somewhere. Any ideas??

The problem is you havent committed the `.gitignore` file yet, so git doesnt know what to exclude. Try adding the following to a .gitignore file, add and committing that file and see what happens


```
HELP.md
.gradle
build/
!gradle/wrapper/gradle-wrapper.jar
!**/src/main/**/build/
!**/src/test/**/build/

### STS ###
.apt_generated
.classpath
.factorypath
.project
.settings
.springBeans
.sts4-cache
bin/
!**/src/main/**/bin/
!**/src/test/**/bin/

### IntelliJ IDEA ###
.idea
*.iws
*.iml
*.ipr
out/
!**/src/main/**/out/
!**/src/test/**/out/

### NetBeans ###
/nbproject/private/
/nbbuild/
/dist/
/nbdist/
/.nb-gradle/

### VS Code ###
.vscode/
```

2022-01-25 20:52 UTC, merged